name: appdomoral
description: Cola no Moral


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  flutter_custom_clippers: ^1.0.4
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.2
  flutter_images_slider: ^0.0.2
  scoped_model: ^1.0.1
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  firebase_analytics: ^5.0.2
  firebase_messaging: ^5.1.5
  google_sign_in: ^4.0.7
  cached_network_image: ^1.1.1
  flutter_facebook_login: ^2.0.1
  advanced_splashscreen: ^0.0.1
  firebase_core: ^0.4.0+9
  flutter_plugin_pdf_viewer: ^1.0.7
  path_provider: ^1.3.0
  share: ^0.6.2+1
  rate_my_app: ^0.4.0
  dio: ^2.2.2
  sqflite: ^1.1.6+5
  fl_chart: ^0.2.2
  flutter_youtube: ^1.1.6
  back_button_interceptor: ^4.1.1
  flutter_html: ^0.11.0
  provider: ^3.1.0
  day_night_switch: ^0.0.2+1
  image_picker: ^0.5.3+1
  firebase_storage: ^3.0.6
  fluttertoast: ^3.1.3
  bottom_navy_bar: ^5.2.0
  flutter_spinkit: "^4.0.0"
  animated_card: ^1.0.0+8
  expandable: ^3.0.1
  date_format: ^1.0.6
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.13.0
  flutter_multiselect: ^0.4.0
  flutter_plugin_tts: ^1.0.2
  skeleton_text: ^1.0.0
  fab_circular_menu: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
  - assets/
  - assets/images/
  - assets/images/icons/
  - assets/pdfs/CGD_compact.pdf
  - assets/pdfs/CODIGO_compact.pdf
  - assets/pdfs/ESTATUTO_compact.pdf
  - assets/pdfs/CF88Art5_compact.pdf
  - assets/pdfs/CF88Art144_compact.pdf
  - assets/pdfs/PCEPCLei12.124_93App.pdf
  - assets/pdfs/PCLEI16004App_compact.pdf
  - assets/pdfs/PCLEIN15.990App_compact.pdf
  - assets/json/pmce_disciplinas.json
  - assets/json/disciplinas.json
  - assets/json/bancas.json
  - assets/json/anos.json
  - assets/json/cargos.json
  - assets/json/orgaos.json
  - assets/json/lei.json

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

